### ISSUE TITLE
Feature Request: configuration of screenshot interval

### ISSUE THREAD

**Issue by xyb** [arkohut/pensieve#12]
The screenshot interval should be made configurable rather than [hard-coded](https://github.com/arkohut/pensieve/blob/4e7577c6c4fce71825c5eece2824ca84c1c92390/memos/record.py#L327) to allow users to adjust the capture frequency based on their needs and storage constraints.

**Comment by arkohut** [comment]
I can add another config for that. Do you want to make the interval longer?

**Comment by sfranky** [comment]
I'm loving this project, thanks for your efforts!!
For me, it would make sense for the interval to be longer, yes. Especially since it almost takes the same time to process each image as it does to capture it, which feels a little stressful !!

**Comment by arkohut** [comment]
> I'm loving this project, thanks for your efforts!! For me, it would make sense for the interval to be longer, yes. Especially since it almost takes the same time to process each image as it does to capture it, which feels a little stressful !!

Ok, I will make it configurable by the config file. And you mean the processing time of OCR takes maybe 5 seconds?

**Comment by sfranky** [comment]
Not just OCR, i enabled the local VLM option, but I don't really know what I'm doing yet so....
I'm on an nvidia 4070Ti 12GB card.

**Comment by aisensiy** [comment]
Wow, which VLM are you using?

**Comment by sfranky** [comment]
i just used the defaults

**Comment by arkohut** [comment]
Hi, https://github.com/arkohut/pensieve/commit/ebb74c9208e7c611123d3700d37f8a44091001de it is supported. Please update to 0.18.9 to get the new feature.

**Comment by arkohut** [comment]
The video is lost...BTW you have to `memos stop && memo start` to make the new configuration work.

**Comment by sfranky** [comment]
tl;dw it showed about 4s/it more or less for a few images. Yes I always restart it like this, thx

**Comment by xyb** [comment]
Thank you for such a quick update!
