### ISSUE TITLE
Is `memos scan` necessary to index all screenshots?

### ISSUE THREAD

**Issue by aivajoe** [arkohut/pensieve#16]
It seems to me that having all screenshots fully indexed is important for this tool to be useful.
In its default mode, does it eventually end up indexing all screenshots? Or does the user need to manually start a loop of `memo scan` in the background to ensure all screenshots are indexed eventually?
Thank you!

**Comment by aivajoe** [comment]
BTW I'm referring to this part of the readme: https://github.com/arkohut/pensieve?tab=readme-ov-file#full-indexing

**Comment by aivajoe** [comment]
It seems like `memos scan` might be necessary to have running in a loop permanently, otherwise only very few screenshots will actually be fully processed. On my Mac M1, it takes a minute or two to index a single screenshot.

**Comment by arkohut** [comment]
Are you using ollama with the VLM model?

**Comment by aivajoe** [comment]
> Are you using ollama with the VLM model?

Yes.

**Comment by arkohut** [comment]
The VLM can be slow. Although you are using a M1 Mac but the performance may still be quite bad comparing Nvidia GPU. I will give you more performance benchmarks on my M1 Max as soon as possible.
