### ISSUE TITLE
无法初始化

### ISSUE THREAD

**Issue by Sc-Eric-B** [arkohut/pensieve#17]
![image](https://github.com/user-attachments/assets/3b649259-7397-446b-bd53-9f8b319e6075)
命令失败

**Comment by Sc-Eric-B** [comment]
3.13

**Comment by Sc-Eric-B** [comment]
![image](https://github.com/user-attachments/assets/108cc505-76b7-4d0d-8731-75ab911f5ba3)
python 版本3.13 memos版本 0.1.0

**Comment by Sc-Eric-B** [comment]
> 您使用的是哪个版本？尝试 `pip show memos` 获取版本。

![image](https://github.com/user-attachments/assets/8b127c0c-88a2-40a9-b97b-11d7143e7859)
Python 版本 3.13 备忘录版本 0.1.0

**Comment by Sc-Eric-B** [comment]
> Which version are you using? Try `pip show memos` to get the version.
![image](https://github.com/user-attachments/assets/c80728df-c942-44e1-85d3-84fc9fbe5b8c)
尝试本地安装，报错

**Comment by usernamedd** [comment]
the same issue hit me

**Comment by arkohut** [comment]
> > Which version are you using? Try `pip show memos` to get the version.
> > ![image](https://private-user-images.githubusercontent.com/69334742/387898381-c80728df-c942-44e1-85d3-84fc9fbe5b8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQzMzQsIm5iZiI6MTczMjA3NDAzNCwicGF0aCI6Ii82OTMzNDc0Mi8zODc4OTgzODEtYzgwNzI4ZGYtYzk0Mi00NGUxLTg1ZDMtODRmYzlmYmU1YjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNmY1MDA3MGYxOTI4NzczZjczOGNjNWY1NTk1YTZhNzhjZGJhZjNiNmNlZmQ2Y2ZmMWQ1ZDkwMjExOTgzMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GZjsEEitXkH_j2E-AjONeUMm8idJBcouhlmshAGu23E)
> > 尝试本地安装，报错

Python 3.13 is such a new version. Some dependencies of `pensieve` are still not support Python 3.13. Please try using Python 3.12.
