### ISSUE TITLE
建议建立一个社群供大家讨论

### ISSUE THREAD

**Issue by chmod777john** [arkohut/pensieve#19]
Awesome project! 我觉得可以弄一个社群（微信群或者 Discord），这样用户们可以实时的交流，有类似于头脑风暴的效果，可以碰撞出一些新的需求，同时反馈意见也会更及时。

还有些用户可能是被安利来的，也许Github Issue对这部分用户来说会有点困难，小白用户也可以在群里讨论，当讨论出一个比较明确的需求时，再发起一个正式的 issue 。

后续作者需要时，我将移交群管理权限

![image](https://github.com/user-attachments/assets/9827c934-5f5e-469b-9aa8-2445449d03f8)

Discord: https://discord.gg/Vm6G3jFDXm

**Comment by arkohut** [comment]
谢谢你的好意，不过我不知道这样一个小项目是否值得
