### ISSUE TITLE
本地有截图，网站搜索无结果

### ISSUE THREAD

**Issue by yenanjing** [arkohut/pensieve#20]
感谢您分享如此好用的工具，我尝试使用时全程很丝滑，但是打开网站没有搜索结果，然而本地有截图文件，这是什么原因呢？
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/54b95262-1229-4618-b32c-261ae7a8268b">
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/b7845791-06a9-4476-bc87-2f851c040fbc">

**Comment by arkohut** [comment]
麻烦提供下三个信息：

1. `memos config` 的结果
2. `memos ps` 的结果
3. `memos lib ls` 的结果

谢谢

**Comment by yenanjing** [comment]
我在运行memos ps时发现watch is not running，重新运行memos watch后网页正常显示了，感谢！
<img width="444" alt="image" src="https://github.com/user-attachments/assets/6aaf0fe1-34cd-412e-99c3-a9c785b7fef0">
