### ISSUE TITLE
能实现客户端只负责截屏, 服务端提供web+存储+计算这样的效果吗?

### ISSUE THREAD

**Issue by Alt-er** [arkohut/pensieve#21]

**Comment by arkohut** [comment]
可否介绍下你具体的场景呢？

**Comment by Alt-er** [comment]
因为需要记录的机器上没有足够的存储和计算资源, 比如mac mini 256g 16g 这样的配置. 如果放到一个有足够资源的机器上跑服务端, 这样客户端就没有任何压力了, 且服务端可以同时记录多个机器的记录. 
当然这只是我的一个想法, 不能实现也没什么

**Comment by arkohut** [comment]
对于计算，`pensieve` 完全支持的，可以通过调整配置使用其他机器上的 api 调用获取计算能力。
对于存储，原生没有做这样子的支持，不过我想可以这样子实现：

1. 准备一个网盘 mount 到 mac mini 上
2. 调整 `~/.memos/config.yaml` 中存储数据的目录到网盘

不过我觉得既然是一个 mac mini 的话，是不是也可以直接插一个移动硬盘？因为毕竟网盘的话重启之后是不是需要重新 mount 的？

**Comment by rty813** [comment]
@arkohut 截图、数据库，这些都占大头。数据库可以考虑允许指定外部数据库，截图可以考虑接入s3存储，这样的话性能更好。

**Comment by rty813** [comment]
尤其是截图，4s一张，一天就能产生几千张图片，一个月就是数十万张照片，这对于windows的文件存储方式来说压力太大了。估计到时候想看看文件夹大小都会卡死，这时候对象存储就有很明显的优势了，检索、统计，都性能更好。

**Comment by Alt-er** [comment]
我还有一个 m1 mbp 16G , 如果外接移动硬盘就不方便携带了,  挂载网盘这个得看看稳定性了, 暂时是先存本地的.
