### ISSUE TITLE
[feature request] 希望能增加生成视频的功能

### ISSUE THREAD

**Issue by rty813** [arkohut/pensieve#24]
场景：有时候可能需要查看某一天大概都做了什么，如果看图片的话，太多太多了，且都是缩略图也看不太清楚。如果能选择某一个时间段，将这段时间的图片通过ffmpeg、opencv等库生成一个视频，就方便太多了

**Comment by rty813** [comment]
再补充一条，现在筛选时间不能选择时间，只能精确到日，有点不太方便

**Comment by Alt-er** [comment]
我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片,  不知道存储和查询时这个性能消耗大不大

**Comment by arkohut** [comment]
> 再补充一条，现在筛选时间不能选择时间，只能精确到日，有点不太方便

我试试看

**Comment by arkohut** [comment]
> 我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片, 不知道存储和查询时这个性能消耗大不大

有在尝试这个功能，会进一步节省存储空间

**Comment by rty813** [comment]
> 我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片, 不知道存储和查询时这个性能消耗大不大

存成视频的话，H264编码时GOP就需要设置的特别小，每帧都是关键帧，否则会出现查找中间某一帧时，模糊的问题。而GOP设置小了文件就会特别大，本质上我觉得没什么差异，或者有更好的编码方案，否则还是要存图片。

**Comment by arkohut** [comment]
> > 我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片, 不知道存储和查询时这个性能消耗大不大
> 
> 存成视频的话，H264编码时GOP就需要设置的特别小，每帧都是关键帧，否则会出现查找中间某一非关键帧时，由于没有参考而变糊的情况。而GOP设置小了文件就会特别大，本质上我觉得没什么差异，或者有更好的编码方案，否则还是要存图片。

我测试了下，感觉对后续查看内容的影响不大，不过这可能是建立在我的电脑分辨率本来就较高的前提下

**Comment by rty813** [comment]
> > > 我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片, 不知道存储和查询时这个性能消耗大不大
> > 
> > 
> > 存成视频的话，H264编码时GOP就需要设置的特别小，每帧都是关键帧，否则会出现查找中间某一非关键帧时，由于没有参考而变糊的情况。而GOP设置小了文件就会特别大，本质上我觉得没什么差异，或者有更好的编码方案，否则还是要存图片。
> 
> 我测试了下，感觉对后续查看内容的影响不大，不过这可能是建立在我的电脑分辨率本来就较高的前提下。并且这应该就是个可选功能，最后可以按照需求自行选择

你视频中每张图片设置的时长是多少，还是说每张图片只有一帧？

**Comment by rty813** [comment]
> > > 我觉得直接把一天的图片存成视频是不是压缩率会更好? 数据库中记录第几帧就能找到图片, 不知道存储和查询时这个性能消耗大不大
> > 
> > 
> > 存成视频的话，H264编码时GOP就需要设置的特别小，每帧都是关键帧，否则会出现查找中间某一非关键帧时，由于没有参考而变糊的情况。而GOP设置小了文件就会特别大，本质上我觉得没什么差异，或者有更好的编码方案，否则还是要存图片。
> 
> 我测试了下，感觉对后续查看内容的影响不大，不过这可能是建立在我的电脑分辨率本来就较高的前提下。并且这应该就是个可选功能，最后可以按照需求自行选择

好像确实没有损失清晰度。不过体积上并没有压缩，我用opencv生成视频，比原图片还要大了一点。但我觉得这是一个好功能，可以快速预览某天的行动。

**Comment by arkohut** [comment]
这个就需要个人权衡利弊了，这里假设大家更希望通过一些质量损失换取更多存储空间，否则生成视频的不是很有必要了。如果你对这个功能非常感兴趣，希望提前尝试，可以使用 https://github.com/arkohut/pensieve/blob/master/screen_recorder/video_generator.py ，其中 `ffmpeg` 相关的命令可以依据对图像清晰度的需求做调整，不过这部分功能我没有做严格的测试，只是一个非常实验性的工作。

**Comment by Alt-er** [comment]
我了一个将图片转视频的简单测试, 我这边感觉压缩率挺高的

结果:
```
465M	imgs                            所有截图文件, 1500多张webp
465M	imgs_sort
116M	output_264_r30.mp4
208M	output_264_r5.mp4
108M	output_265_r30.mp4
189M	output_265_r5.mp4
```

生成命令:
```
ffmpeg -framerate 5 -i /root/imgs_sort/img%04d.webp -c:v libx265  -r 5 -pix_fmt yuv420p output_265_r5.mp4

ffmpeg -framerate 5 -i /root/imgs_sort/img%04d.webp -c:v libx264  -r 5 -pix_fmt yuv420p output_264_r5.mp4

ffmpeg -framerate 30 -i /root/imgs_sort/img%04d.webp -c:v libx265  -r 30 -pix_fmt yuv420p output_265_r30.mp4

ffmpeg -framerate 30 -i /root/imgs_sort/img%04d.webp -c:v libx264  -r 30 -pix_fmt yuv420p output_264_r30.mp4
```

**Comment by rty813** [comment]
这样子生成，体积变小，和直接压缩原图，降低质量是一样的。我通过`ffmpeg -i output.mp4 frames/output_%04d.jpg`命令将视频中的帧提取出来，然后再和原图对比，能看出差异：
原图：
![image](https://github.com/user-attachments/assets/1445af8f-4e57-49b1-9cc9-ee31a4c968ee)

视频帧：
![image](https://github.com/user-attachments/assets/8fa82aed-c3ce-4c76-ac18-abf7b454911f)

**Comment by rty813** [comment]
> 这里假设大家更希望通过一些质量损失换取更多存储空间，否则就没必要生成视频了。
存储空间是其中一点，主要还是想通过视频能快速预览一天的行动轨迹，图片总是不太方便。

**Comment by arkohut** [comment]
那我这里下一个结论了哦，会增加这样的功能，但依然是主动通过命令调用实现的
