### ISSUE TITLE
修改base_dir后，watch进程未生效

### ISSUE THREAD

**Issue by rty813** [arkohut/pensieve#27]
我将base_dir修改为`W:/memos`后，watch进程日志显示仍然在使用原来的`~/.memos`路径。
![image](https://github.com/user-attachments/assets/bce8c049-65b0-434a-afa0-45527151e465)

![image](https://github.com/user-attachments/assets/6b58e02c-c8b5-4a32-91a5-27f700ab02be)

**Comment by rty813** [comment]
database中存储的路径仍然是老的路径，因此只改配置文件似乎没有用

**Comment by arkohut** [comment]
If you changed the `base_dir` do you copy the `database.db` to the new location? If that is true, it means the original configuration in the database is also moved to the new location.  Use command `memos lib ls` to show current Folders.

**Comment by rty813** [comment]
After I changed the base_dir, I also moved database.db to the new location. But `watch` process still uses the old path. I checked the folders table in database and found that the `path` is still the old path.

**Comment by arkohut** [comment]
If there aren’t many files, you can just copy the screenshots to the new location and reindex.
