### ISSUE TITLE
[feature request] 希望能调用NPU代替CPU进行一些计算

### ISSUE THREAD

**Issue by wzp100** [arkohut/pensieve#29]
使用场景：目前各家的最新CPU都说自己的NPU算力如何如何，但是目前用户能够用到的应用几乎没有。所以能不能调用电脑NPU进行一些处理进而减少CPU占用顺便降低功耗。微软的recall的设想应该也是本地调用NPU进行处理。另外想问下当下调用npu是不是还比较困难

https://www.amd.com/zh-cn/developer/resources/ryzen-ai-software.html

**Comment by arkohut** [comment]
目前项目使用的 ml 的 model 主要是这些形式的：

1. ocr: paddleocr
2. vlm: ollama
3. embedding: ollama / torch

那如果想省事的话，只要这些框架 / 工具对 NPU 有了支持，那么 Pensieve 就可以立即支持了。
