### ISSUE TITLE
希望增加开关，允许对每张图片都进行 OCR

### ISSUE THREAD

**Issue by zj1123581321** [arkohut/pensieve#30]
当前版本 v0.20.0

观察下来当下似乎只有画面变动比较大的时候，才会调用  ocr+ vlm 提取图片中的信息。
vlm 非常消耗资源，这个逻辑可以理解。

但 ocr 在现代的设备上占用资源应该没那么高，能否允许用户自行决定是否对每一张图片都进行离线 ocr？或者设定一定的相似度阈值也可以。

----
典型场景就是：我回溯网页、文档，可能只记得一个关键词，这个时候需要有 ocr 的信息才能搜索到这张图片。

**Comment by arkohut** [comment]
https://github.com/arkohut/pensieve/releases/tag/v0.23.2 Try this new release, but you must update the config file at the same time.
