### ISSUE TITLE
无法浏览服务网页

### ISSUE THREAD

**Issue by BryceWG** [arkohut/pensieve#33]
Windows11 24H2, chrome和firefox都尝试过,网页成功加载了图标但是没有内容:
![bb0drmkc awo](https://github.com/user-attachments/assets/f9868280-aff6-41ee-a763-af11ae56d6f1)

**Comment by arkohut** [comment]
似乎和这个 issue 是同一个问题？可否打开调试页面看看有没有报错信息呢

https://github.com/arkohut/pensieve/issues/18#issuecomment-2487660778

**Comment by BryceWG** [comment]
![u41oe3bw mio](https://github.com/user-attachments/assets/c84c7705-4af0-4e32-9859-b1beea13931f)

**Comment by arkohut** [comment]
可否执行这个命令返回给我：

```sh
python -c "import mimetypes; print (mimetypes.guess_type('_app/immutable/entry/app.ae4ec061.js'))"
```

**Comment by arkohut** [comment]
Please try the latest version `0.21.3`.

**Comment by BryceWG** [comment]
升级之后可以打开了,(*ゝω・)ﾉThanks!
