### ISSUE TITLE
OCR Plugin on another computer

### ISSUE THREAD

**Issue by tcsenpai** [arkohut/pensieve#6]
As the OCR plugin is very heavy on the CPU, I managed to follow the README.md for the OCR plugin and start it on another PC in my LAN.

When I configure, either manually or with the plugin command, the OCR endpoint to be remote, I get always "500 Error" with "NoneType" received by the OCR endpoint.

Configuration:

![image](https://github.com/user-attachments/assets/c141f1b7-ae1f-433b-a8d0-5011d7b59d8e)

**Comment by arkohut** [comment]
Are you using the file https://github.com/arkohut/pensieve/blob/master/memos/plugins/ocr/server.py ? It works for me...

<img width="745" alt="ocr" src="https://github.com/user-attachments/assets/7a528e77-17bc-4702-a139-7df308ad053e">


Can you show more logs and error messages about this.

**Comment by tcsenpai** [comment]
Yes I am using it, on another computer indeed.

The error I get is:

## Server

![image](https://github.com/user-attachments/assets/53d2ceb4-c979-4fca-8d05-31c2c7788729)

## OCR Plugin server.py (running on a LAN address)

![clipboard_2024-11-18_11-59](https://github.com/user-attachments/assets/ebfb5714-82f8-41fa-bf42-931594751b10)

## Additional notes

- The embeddings endpoint (ollama) works
- The multimodal model (ollama) works
- They both are on the same PC running the OCR plugin

**Comment by arkohut** [comment]
Could you please show the full commands to start up the ocr predict server.

**Comment by tcsenpai** [comment]
I just run `uvicorn server:app --host 0.0.0.0 --port 5555` on the PC I want to use as a local predict server. I had to use `uvicorn server:app` and not `uvicorn main:app` as the `app` object is into server.py . Also I had to `pip install memos` anyway on that computer else it would complain about dependencies missing.

**Comment by arkohut** [comment]
That’s so weird. I’m using the same method, and it works for me. Based on your log, it seems like there’s no indication of which inference engine is being used. For instance, in my logs, it shows that I’m using onnxruntime CPU.

**Comment by tcsenpai** [comment]
What data do the client sends to the server? I am on Linux using the PR I opened, could it be that?

**Comment by arkohut** [comment]
You can open link http://localhost:5555/predict to see the doc about the api.

**Comment by tcsenpai** [comment]
It spawns 405 Method Not Allowed on the OCR Plugin Server console, both with localhost on the OCR Plugin Server PC and through lan.

![image](https://github.com/user-attachments/assets/300918ba-c554-461e-9557-63bedbcb5566)

**Comment by rty813** [comment]
@arkohut I used ocr plugin in master branch, and same issue occured.
![image](https://github.com/user-attachments/assets/2c5a4cb9-0c46-420e-a748-e926d1c33ee7)
![image](https://github.com/user-attachments/assets/bcbdb756-5637-417a-8000-d7111660408a)

**Comment by rty813** [comment]
I know the reason. Because you initialize `process_pool` in the `if __name__ == '__main__'` entry. But if you start it through `uvicorn`, this entry will not be executed. Therefore, `process_pool` will not be initialized, but `None`

**Comment by rty813** [comment]
share my dockerfile:
```
FROM python:3.12-slim

RUN sed -i 's@http://deb.debian.org@http://mirrors.tuna.tsinghua.edu.cn@g' /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get install -y --no-install-recommends libglib2.0-0 libgl1 \
    && rm -rf /var/lib/apt/lists/*

ADD requirements.txt /tmp/
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /tmp/requirements.txt

WORKDIR /root/ocr
ADD . .
ADD models/* /usr/local/lib/python3.12/site-packages/rapidocr_onnxruntime/models/

EXPOSE 8000
CMD [ "python3", "server.py", "--port", "8000" ]
```

requirements.txt:
```
rapidocr_onnxruntime
httpx
fastapi
uvicorn
memos
```

logs:
```
root@104 ~/z/ocr# docker logs -f ocr
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:__main__:Initialized OCR with RapidOCR ONNX Runtime (CPU)
INFO:     192.168.3.123:27449 - "POST /predict HTTP/1.1" 200 OK
INFO:     192.168.3.123:3123 - "POST /predict HTTP/1.1" 200 OK
INFO:     192.168.3.123:3136 - "POST /predict HTTP/1.1" 200 OK
INFO:     192.168.3.123:6954 - "POST /predict HTTP/1.1" 200 OK
INFO:     192.168.3.123:7014 - "POST /predict HTTP/1.1" 200 OK
```

![image](https://github.com/user-attachments/assets/e6e0834a-0008-4da2-b8fb-2032a0c357d9)

**Comment by arkohut** [comment]
> I know the reason. Because you initialize `process_pool` in the `if __name__ == '__main__'` entry. But if you start it through `uvicorn`, this entry will not be executed. Therefore, `process_pool` will not be initialized, but `None`

Yes, you are right. I will fix such a bug.

**Comment by arkohut** [comment]
> > I know the reason. Because you initialize `process_pool` in the `if __name__ == '__main__'` entry. But if you start it through `uvicorn`, this entry will not be executed. Therefore, `process_pool` will not be initialized, but `None`
> 
> Great debugging work. I will wait for the fix and test on my instance as well.

The work is already done. Check it out!

**Comment by tcsenpai** [comment]
aaaaand it works :) Kudos!
